// These are the locators seen in the Home Page

module.exports = {
    //HomePage
    loc_xpath_login_link: "//a[@class='item-link'][contains(.,'login') or contains(.,'Inloggen')]",
    loc_xpath_myjumbo_button: "//button[@id='jum_user_menu_large_button']",
    loc_xpath_login_button: "//input[@id='login-button']",
    loc_xpath_products_menu: "//a[@class='nav-menu-item-link'][contains(.,'Producten') or contains(.,'Products')]",
    loc_xpath_offers_menu: "//a[@class='nav-menu-item-link'][contains(.,'Aanbiedingen & acties') or contains(.,'Offers & promotions')]",
    loc_xpath_recipes_menu: "//a[@class='nav-menu-item-link'][contains(.,'Recepten') or contains(.,'Recipes')]",
    loc_xpath_accept_cookie_button: "//*[@id='onetrust-accept-btn-handler']",
    loc_xpath_basket_button: "//button[@data-testautomation='basket-button'][@class='jum-button jum-button compact no-price']",
    loc_xpath_handylist_label: "//div[@class='carousel jum-list-overview-carousel']/preceding-sibling::h3[@data-testid='jum-heading-markdown']",
    loc_xpath_searchbar: "//form[@analytics-tag='search']//input[@name='searchTerms']",
    loc_xpath_searchbar_tooltip: "//div[@class='search-bar-tool-tip']",
    loc_xpath_searchbar_header: "//li[@class='search-bar-suggestions-header header-line-item']",
    loc_xpath_searchbar_suggestions_list: "//li[@class='search-bar-suggestions-section']",
    loc_xpath_searchbar_button_disabled: "//button[@data-testid='jum-button'][@class='jum-button search-bar-button compact disabled']",
    loc_xpath_searchbar_button_enabled: "//button[@data-testid='jum-button'][@class='jum-button search-bar-button compact']",
    loc_xpath_searchbar_x_button: "//button[@class='jum-button search-bar-clear-icon-desktop tertiary']",

    //Products menu
    loc_xpath_products_sub_menu_1: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Aardappelen, groente en fruit') or contains(.,'Potatoes, vegetables and fruit')]",
    loc_xpath_products_sub_menu_1_header: "//span[@class='nav-menu-sub-title'][contains(.,'Aardappelen, groente en fruit') or contains(.,'Potatoes, vegetables and fruit')]",
	  loc_xpath_products_sub_menu_1_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Aardappelen, groente en fruit') or contains(.,'Potatoes, vegetables and fruit')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",
    loc_xpath_products_sub_menu_2: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Vlees, vis, vegetarisch') or contains(.,'Meat, fish, vegetarian')]",
    loc_xpath_products_sub_menu_2_header: "//span[@class='nav-menu-sub-title'][contains(.,'Vlees, vis, vegetarisch') or contains(.,'Meat, fish, vegetarian')]",
	  loc_xpath_products_sub_menu_2_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Vlees, vis, vegetarisch') or contains(.,'Meat, fish, vegetarian')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",
    loc_xpath_products_sub_menu_3: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Verse maaltijden en gemak') or contains(.,'Fresh meals and convenience')]",
    loc_xpath_products_sub_menu_3_header: "//span[@class='nav-menu-sub-title'][contains(.,'Verse maaltijden en gemak') or contains(.,'Fresh meals and convenience')]",	
	  loc_xpath_products_sub_menu_3_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Verse maaltijden en gemak') or contains(.,'Fresh meals and convenience')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",	
    loc_xpath_products_sub_menu_4: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Brood en gebak') or contains(.,'Bread and pastries')]",
    loc_xpath_products_sub_menu_4_header: "//span[@class='nav-menu-sub-title'][contains(.,'Brood en gebak') or contains(.,'Bread and pastries')]",
    loc_xpath_products_sub_menu_4_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Brood en gebak') or contains(.,'Bread and pastries')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",	
    loc_xpath_products_sub_menu_5: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Vleeswaren, kaas en tapas') or contains(.,'Cold cuts, cheese and tapas')]",
    loc_xpath_products_sub_menu_5_header: "//span[@class='nav-menu-sub-title'][contains(.,'Vleeswaren, kaas en tapas') or contains(.,'Cold cuts, cheese and tapas')]",
    loc_xpath_products_sub_menu_5_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Vleeswaren, kaas en tapas') or contains(.,'Cold cuts, cheese and tapas')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",
    loc_xpath_products_sub_menu_6: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Zuivel, eieren, boter') or contains(.,'Dairy, eggs, butter')]",
    loc_xpath_products_sub_menu_6_header: "//span[@class='nav-menu-sub-title'][contains(.,'Zuivel, eieren, boter') or contains(.,'Dairy, eggs, butter')]",
	  loc_xpath_products_sub_menu_6_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Zuivel, eieren, boter') or contains(.,'Dairy, eggs, butter')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",
    loc_xpath_products_sub_menu_7: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Conserven, soepen, sauzen, oliën') or contains(.,'Perserves, soups, sauces, oils')]",
    loc_xpath_products_sub_menu_7_header: "//span[@class='nav-menu-sub-title'][contains(.,'Conserven, soepen, sauzen, oliën') or contains(.,'Perserves, soups, sauces, oils')]",
    loc_xpath_products_sub_menu_7_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Conserven, soepen, sauzen, oliën') or contains(.,'Perserves, soups, sauces, oils')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",	
    loc_xpath_products_sub_menu_8: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Wereldkeukens, kruiden, pasta en rijst') or contains(.,'World cuisines, spices, pasta and rice')]",
    loc_xpath_products_sub_menu_8_header: "//span[@class='nav-menu-sub-title'][contains(.,'Wereldkeukens, kruiden, pasta en rijst') or contains(.,'World cuisines, spices, pasta and rice')]",	
    loc_xpath_products_sub_menu_8_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Wereldkeukens, kruiden, pasta en rijst') or contains(.,'World cuisines, spices, pasta and rice')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",
    loc_xpath_products_sub_menu_9: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Ontbijt, broodbeleg en bakproducten') or contains(.,'Breakfast, spreads and baking products')]",
    loc_xpath_products_sub_menu_9_header: "//span[@class='nav-menu-sub-title'][contains(.,'Ontbijt, broodbeleg en bakproducten') or contains(.,'Breakfast, spreads and baking products')]",
    loc_xpath_products_sub_menu_9_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Ontbijt, broodbeleg en bakproducten') or contains(.,'Breakfast, spreads and baking products')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",
    loc_xpath_products_sub_menu_10: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Koek, snoep, chocolade en chips') or contains(.,'Cookie, candy, chocolate and chips')]",
    loc_xpath_products_sub_menu_10_header: "//span[@class='nav-menu-sub-title'][contains(.,'Koek, snoep, chocolade en chips') or contains(.,'Cookie, candy, chocolate and chips')]",
    loc_xpath_products_sub_menu_10_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Koek, snoep, chocolade en chips') or contains(.,'Cookie, candy, chocolate and chips')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",	
    loc_xpath_products_sub_menu_11: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Fris, sap, koffie, thee') or contains(.,'Fresh, juice, coffee, tea')]",
    loc_xpath_products_sub_menu_11_header: "//span[@class='nav-menu-sub-title'][contains(.,'Fris, sap, koffie, thee') or contains(.,'Fresh, juice, coffee, tea')]",
    loc_xpath_products_sub_menu_11_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Fris, sap, koffie, thee') or contains(.,'Fresh, juice, coffee, tea')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",	
	  loc_xpath_products_sub_menu_12: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Bier en wijn') or contains(.,'Beer and wine')]",
    loc_xpath_products_sub_menu_12_header: "//span[@class='nav-menu-sub-title'][contains(.,'Bier en wijn') or contains(.,'Beer and wine')]",
    loc_xpath_products_sub_menu_12_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Bier en wijn') or contains(.,'Beer and wine')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",	
    loc_xpath_products_sub_menu_13: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Diepvries') or contains(.,'Freezer')]",
    loc_xpath_products_sub_menu_13_header: "//span[@class='nav-menu-sub-title'][contains(.,'Diepvries') or contains(.,'Freezer')]",
    loc_xpath_products_sub_menu_13_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Diepvries') or contains(.,'Freezer')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",	
    loc_xpath_products_sub_menu_14: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Drogisterij') or contains(.,'Drugstore')]",
    loc_xpath_products_sub_menu_14_header: "//span[@class='nav-menu-sub-title'][contains(.,'Drogisterij') or contains(.,'Drugstore')]",
    loc_xpath_products_sub_menu_14_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Drogisterij') or contains(.,'Drugstore')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",	
    loc_xpath_products_sub_menu_15: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Baby, peuter') or contains(.,'Baby, toddlert')]",
    loc_xpath_products_sub_menu_15_header: "//span[@class='nav-menu-sub-title'][contains(.,'Baby, peuter') or contains(.,'Baby, toddlert')]",
    loc_xpath_products_sub_menu_15_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Baby, peuter') or contains(.,'Baby, toddlert')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",	
    loc_xpath_products_sub_menu_16: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Huishouden, dieren, servicebalie') or contains(.,'Household, animals, service desk ')]",
    loc_xpath_products_sub_menu_16_header: "//span[@class='nav-menu-sub-title'][contains(.,'Huishouden, dieren, servicebalie') or contains(.,'Household, animals, service desk ')]",
    loc_xpath_products_sub_menu_16_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Huishouden, dieren, servicebalie') or contains(.,'Household, animals, service desk ')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",	
    loc_xpath_products_sub_menu_17: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Handige lijstjes') or contains(.,'Handy lists')]",	
    loc_xpath_products_sub_menu_18: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Nieuw assortiment') or contains(.,'New range')]",

    //Offers menu
    loc_xpath_offers_sub_menu_1: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Aanbiedingen') or contains(.,'Offers')]",
    loc_xpath_offers_sub_menu_1_header: "//span[@class='nav-menu-sub-title'][contains(.,'Aanbiedingen') or contains(.,'Offers')]",
	  loc_xpath_offers_sub_menu_1_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Aanbiedingen') or contains(.,'Offers')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",
    loc_xpath_offers_sub_menu_2: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Goedkoop bezorgen') or contains(.,'Cheap delivery')]",
    loc_xpath_offers_sub_menu_2_header: "//span[@class='nav-menu-sub-title'][contains(.,'Goedkoop bezorgen') or contains(.,'Cheap delivery')]",
    loc_xpath_offers_sub_menu_3: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Win- & spaaracties') or contains(.,'Win & save promotions')]",
    loc_xpath_offers_sub_menu_3_header: "//span[@class='nav-menu-sub-title'][contains(.,'Win- & spaaracties') or contains(.,'Win & save promotions')]",
	  loc_xpath_offers_sub_menu_3_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Win- & spaaracties') or contains(.,'Win & save promotions')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",
    loc_xpath_offers_sub_menu_4: "//li[@class='nav-menu-collapsed-item nav-menu-collapsed-item-big'][contains(.,'Jumbo Extra') or contains(.,'Jumbo Extras')]",
    loc_xpath_offers_sub_menu_4_header: "//span[@class='nav-menu-sub-title'][contains(.,'Jumbo Extra') or contains(.,'Jumbo Extras')]",

    //Recipes menu
    loc_xpath_recipes_sub_menu_1: "//li[@class='nav-menu-collapsed-item'][contains(.,'Wat eten we?') or contains(.,'What are we eating?')]",
    loc_xpath_recipes_sub_menu_1_header: "//span[@class='nav-menu-sub-title'][contains(.,'Wat eten we?') or contains(.,'What are we eating?')]",
	  loc_xpath_recipes_sub_menu_1_view_all_link: "//span[@class='nav-menu-sub-title'][contains(.,'Wat eten we?') or contains(.,'What are we eating?')]/following-sibling::a[contains(.,'View all') or contains(.,'Bekijk alles')]",
    loc_xpath_recipes_sub_menu_2: "//li[@class='nav-menu-collapsed-item'][contains(.,'Weekmenu') or contains(.,'Weekly menu')]",
    loc_xpath_recipes_sub_menu_2_header: "//span[@class='nav-menu-sub-title'][contains(.,'Weekmenu') or contains(.,'Weekly menu')]",
    loc_xpath_recipes_sub_menu_3: "//li[@class='nav-menu-collapsed-item'][contains(.,'Klaar in 20 minuten') or contains(.,'Ready in 20 minutes')]",
    loc_xpath_recipes_sub_menu_3_header: "//span[@class='nav-menu-sub-title'][contains(.,'Klaar in 20 minuten') or contains(.,'Ready in 20 minutes')]",	
    loc_xpath_recipes_sub_menu_4: "//li[@class='nav-menu-collapsed-item'][contains(.,'Hoofdgerechten') or contains(.,'Main dishes')]",
    loc_xpath_recipes_sub_menu_4_header: "//span[@class='nav-menu-sub-title'][contains(.,'Hoofdgerechten') or contains(.,'Main dishes')]",
    loc_xpath_recipes_sub_menu_5: "//li[@class='nav-menu-collapsed-item'][contains(.,'Makkelijke recepten') or contains(.,'Easy recipes')]",
    loc_xpath_recipes_sub_menu_5_header: "//span[@class='nav-menu-sub-title'][contains(.,'Makkelijke recepten') or contains(.,'Easy recipes')]",
    loc_xpath_recipes_sub_menu_6: "//li[@class='nav-menu-collapsed-item'][contains(.,'Budget recepten') or contains(.,'Budget recipes')]",
    loc_xpath_recipes_sub_menu_6_header: "//span[@class='nav-menu-sub-title'][contains(.,'Budget recepten') or contains(.,'Budget recipes')]",

    //Handy lists
    loc_xpath_handylists_list: "//h2[@class='jum-heading title h5']/a",
    loc_xpath_viewlist_button: "//a[@aria-label='View all lists' or @aria-label='Bekijk alle lijstjes']"
  };


  

